### ISSUE TITLE
Logins fail repeatedly with v1 .id accounts

### ISSUE THREAD

**Issue by dantrevino** [blockstack/blockstack-app#2237]
Failed to load resource: net::ERR_FAILED
instrument.js:109 TypeError: Failed to fetch
    at instrument.js:136:34
    at fetchUtil.esm.js:22:20
    at f (runtime.esm.js:66:19)
    at Generator._invoke (runtime.esm.js:283:24)
    at Generator.next (runtime.esm.js:119:23)
    at i (_rollupPluginBabelHelpers.js:3:20)
    at a (_rollupPluginBabelHelpers.js:25:9)
    at _rollupPluginBabelHelpers.js:32:7
    at new Promise (<anonymous>)
    at _rollupPluginBabelHelpers.js:21:12
    at a (fetchUtil.esm.js:35:24)
    at s (fetchUtil.esm.js:6:24)
    at verification.esm.js:102:20
    at f (runtime.esm.js:66:19)
    at Generator._invoke (runtime.esm.js:283:24)
    at Generator.next (runtime.esm.js:119:23)
    at v (_rollupPluginBabelHelpers.js:3:20)
    at s (_rollupPluginBabelHelpers.js:25:9)
    at _rollupPluginBabelHelpers.js:32:7
    at new Promise (<anonymous>)
    at _rollupPluginBabelHelpers.js:21:12
    at Kt (verification.esm.js:156:37)
    at Ft (verification.esm.js:54:37)
    at verification.esm.js:310:159
    at f (runtime.esm.js:66:19)
    at Generator._invoke (runtime.esm.js:283:24)
    at Generator.next (runtime.esm.js:119:23)
    at v (_rollupPluginBabelHelpers.js:3:20)
    at s (_rollupPluginBabelHelpers.js:25:9)
    at _rollupPluginBabelHelpers.js:32:7
    at new Promise (<anonymous>)
    at _rollupPluginBabelHelpers.js:21:12
    at Vt (verification.esm.js:325:30)
    at Wt (verification.esm.js:299:30)
    at t.<anonymous> (userSession.esm.js:157:22)
    at f (runtime.esm.js:66:19)
    at Generator._invoke (runtime.esm.js:283:24)
    at Generator.next (runtime.esm.js:119:23)
    at v (_rollupPluginBabelHelpers.js:3:20)
    at s (_rollupPluginBabelHelpers.js:25:9)
    at _rollupPluginBabelHelpers.js:32:7
    at new Promise (<anonymous>)
    at t.<anonymous> (_rollupPluginBabelHelpers.js:21:12)
    at t.handlePendingSignIn (userSession.esm.js:314:35)
    at auth.esm.js:78:32
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at i (_rollupPluginBabelHelpers.js:3:20)
    at a (_rollupPluginBabelHelpers.js:25:9)
instrument.js:109 Error checking `doPublicKeysMatchUsername`
instrument.js:109 [Connect] Error during auth request Error
    at t.<anonymous> (userSession.esm.js:167:21)
    at f (runtime.esm.js:66:19)
    at Generator._invoke (runtime.esm.js:283:24)
    at Generator.next (runtime.esm.js:119:23)
    at v (_rollupPluginBabelHelpers.js:3:20)
    at s (_rollupPluginBabelHelpers.js:25:9)
(anonymous) @ instrument.js:109

**Comment by markmhendrickson** [comment]
Are these usernames either expired or renewed? We have relevant issues here for those cases: https://github.com/hirosystems/stacks-wallet-web/issues/504 https://github.com/hirosystems/stacks-wallet-web/issues/1073

**Comment by dantrevino** [comment]
How is it possible to renew? I've never seen any documentation or communication on this.

**Comment by markmhendrickson** [comment]
@larrysalibra is preparing an app for renewals
