### ISSUE TITLE
Error in "Switch account" menu when reading invalid punycode

### ISSUE THREAD

**Issue by badonyx** [blockstack/blockstack-app#2769]
Extension errors out (blank window) when I open my wallet and scroll past an invalid punycode such as `xn--nx.btc`

Related to: https://github.com/hirosystems/stacks-wallet-web/issues/2724

```
dev-tools-warning-log.ts:4  ⚠️ Warning:   Do not paste any code here.   This is a developer tool which could be used to steal your funds.
DevTools failed to load source map: Could not load content for chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/decryption-worker.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
react-dom.production.min.js:216 RangeError: Invalid input
    at error (punycode.es6.js:42:1)
    at decode (punycode.es6.js:235:1)
    at punycode.es6.js:389:1
    at map (punycode.es6.js:57:1)
    at mapDomain (punycode.es6.js:84:1)
    at toUnicode (punycode.es6.js:387:1)
    at use-account-names.ts:18:35
    at Object.useMemo (react-dom.production.min.js:172:113)
    at exports.useMemo (react.production.min.js:23:102)
    at useAccountDisplayName (use-account-names.ts:17:17)
Ni @ react-dom.production.min.js:216
Si.c.payload @ react-dom.production.min.js:217
Cg @ react-dom.production.min.js:130
pi @ react-dom.production.min.js:184
ck @ react-dom.production.min.js:269
bk @ react-dom.production.min.js:250
ak @ react-dom.production.min.js:250
Tj @ react-dom.production.min.js:250
Lj @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
jg @ react-dom.production.min.js:123
ig @ react-dom.production.min.js:122
Jg @ react-dom.production.min.js:237
Oh @ react-dom.production.min.js:170
(anonymous) @ react-urx.esm.js:205
(anonymous) @ urx.esm.js:267
(anonymous) @ urx.esm.js:266
(anonymous) @ urx.esm.js:304
(anonymous) @ urx.esm.js:37
(anonymous) @ urx.esm.js:527
(anonymous) @ urx.esm.js:552
(anonymous) @ urx.esm.js:21
(anonymous) @ urx.esm.js:552
(anonymous) @ urx.esm.js:267
(anonymous) @ urx.esm.js:266
publish @ urx.esm.js:144
(anonymous) @ urx.esm.js:836
(anonymous) @ urx.esm.js:527
(anonymous) @ urx.esm.js:267
(anonymous) @ urx.esm.js:266
(anonymous) @ urx.esm.js:304
(anonymous) @ urx.esm.js:37
(anonymous) @ urx.esm.js:527
(anonymous) @ urx.esm.js:552
(anonymous) @ urx.esm.js:21
(anonymous) @ urx.esm.js:267
(anonymous) @ urx.esm.js:266
publish @ urx.esm.js:144
(anonymous) @ urx.esm.js:836
(anonymous) @ urx.esm.js:527
(anonymous) @ urx.esm.js:267
(anonymous) @ urx.esm.js:266
(anonymous) @ urx.esm.js:37
(anonymous) @ urx.esm.js:21
(anonymous) @ urx.esm.js:267
(anonymous) @ urx.esm.js:266
publish @ urx.esm.js:144
(anonymous) @ urx.esm.js:37
s @ index.m.js:1
(anonymous) @ index.m.js:1
react-dom.production.min.js:216 RangeError: Invalid input
    at error (punycode.es6.js:42:1)
    at decode (punycode.es6.js:235:1)
    at punycode.es6.js:389:1
    at map (punycode.es6.js:57:1)
    at mapDomain (punycode.es6.js:84:1)
    at toUnicode (punycode.es6.js:387:1)
    at use-account-names.ts:18:35
    at Object.useMemo (react-dom.production.min.js:172:113)
    at exports.useMemo (react.production.min.js:23:102)
    at useAccountDisplayName (use-account-names.ts:17:17)
Ni @ react-dom.production.min.js:216
Pi.c.callback @ react-dom.production.min.js:216
Eg @ react-dom.production.min.js:131
Yi @ react-dom.production.min.js:220
dk @ react-dom.production.min.js:259
exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Uj @ react-dom.production.min.js:252
Lj @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
jg @ react-dom.production.min.js:123
ig @ react-dom.production.min.js:122
Jg @ react-dom.production.min.js:237
Oh @ react-dom.production.min.js:170
(anonymous) @ react-urx.esm.js:205
(anonymous) @ urx.esm.js:267
(anonymous) @ urx.esm.js:266
(anonymous) @ urx.esm.js:304
(anonymous) @ urx.esm.js:37
(anonymous) @ urx.esm.js:527
(anonymous) @ urx.esm.js:552
(anonymous) @ urx.esm.js:21
(anonymous) @ urx.esm.js:552
(anonymous) @ urx.esm.js:267
(anonymous) @ urx.esm.js:266
publish @ urx.esm.js:144
(anonymous) @ urx.esm.js:836
(anonymous) @ urx.esm.js:527
(anonymous) @ urx.esm.js:267
(anonymous) @ urx.esm.js:266
(anonymous) @ urx.esm.js:304
(anonymous) @ urx.esm.js:37
(anonymous) @ urx.esm.js:527
(anonymous) @ urx.esm.js:552
(anonymous) @ urx.esm.js:21
(anonymous) @ urx.esm.js:267
(anonymous) @ urx.esm.js:266
publish @ urx.esm.js:144
(anonymous) @ urx.esm.js:836
(anonymous) @ urx.esm.js:527
(anonymous) @ urx.esm.js:267
(anonymous) @ urx.esm.js:266
(anonymous) @ urx.esm.js:37
(anonymous) @ urx.esm.js:21
(anonymous) @ urx.esm.js:267
(anonymous) @ urx.esm.js:266
publish @ urx.esm.js:144
(anonymous) @ urx.esm.js:37
s @ index.m.js:1
(anonymous) @ index.m.js:1
punycode.es6.js:42 Uncaught RangeError: Invalid input
    at error (punycode.es6.js:42:1)
    at decode (punycode.es6.js:235:1)
    at punycode.es6.js:389:1
    at map (punycode.es6.js:57:1)
    at mapDomain (punycode.es6.js:84:1)
    at toUnicode (punycode.es6.js:387:1)
    at use-account-names.ts:18:35
    at Object.useMemo (react-dom.production.min.js:172:113)
    at exports.useMemo (react.production.min.js:23:102)
    at useAccountDisplayName (use-account-names.ts:17:17)
error @ punycode.es6.js:42
decode @ punycode.es6.js:235
(anonymous) @ punycode.es6.js:389
map @ punycode.es6.js:57
mapDomain @ punycode.es6.js:84
toUnicode @ punycode.es6.js:387
(anonymous) @ use-account-names.ts:18
useMemo @ react-dom.production.min.js:172
exports.useMemo @ react.production.min.js:23
useAccountDisplayName @ use-account-names.ts:17
(anonymous) @ switch-account-list-item.tsx:50
Ch @ react-dom.production.min.js:157
li @ react-dom.production.min.js:180
ki @ react-dom.production.min.js:178
ii @ react-dom.production.min.js:177
ck @ react-dom.production.min.js:274
bk @ react-dom.production.min.js:250
ak @ react-dom.production.min.js:250
Tj @ react-dom.production.min.js:250
Lj @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
exports.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
jg @ react-dom.production.min.js:123
ig @ react-dom.production.min.js:122
Jg @ react-dom.production.min.js:237
Oh @ react-dom.production.min.js:170
(anonymous) @ react-urx.esm.js:205
(anonymous) @ urx.esm.js:267
(anonymous) @ urx.esm.js:266
(anonymous) @ urx.esm.js:304
(anonymous) @ urx.esm.js:37
(anonymous) @ urx.esm.js:527
(anonymous) @ urx.esm.js:552
(anonymous) @ urx.esm.js:21
(anonymous) @ urx.esm.js:552
(anonymous) @ urx.esm.js:267
(anonymous) @ urx.esm.js:266
publish @ urx.esm.js:144
(anonymous) @ urx.esm.js:836
(anonymous) @ urx.esm.js:527
(anonymous) @ urx.esm.js:267
(anonymous) @ urx.esm.js:266
(anonymous) @ urx.esm.js:304
(anonymous) @ urx.esm.js:37
(anonymous) @ urx.esm.js:527
(anonymous) @ urx.esm.js:552
(anonymous) @ urx.esm.js:21
(anonymous) @ urx.esm.js:267
(anonymous) @ urx.esm.js:266
publish @ urx.esm.js:144
(anonymous) @ urx.esm.js:836
(anonymous) @ urx.esm.js:527
(anonymous) @ urx.esm.js:267
(anonymous) @ urx.esm.js:266
(anonymous) @ urx.esm.js:37
(anonymous) @ urx.esm.js:21
(anonymous) @ urx.esm.js:267
(anonymous) @ urx.esm.js:266
publish @ urx.esm.js:144
(anonymous) @ urx.esm.js:37
s @ index.m.js:1
(anonymous) @ index.m.js:1
```

**Comment by badonyx** [comment]
Version 3.21.0. The wallet should check for validity of the punycode before trying to render it.

**Comment by edu-stx** [comment]
Fix should be released on Monday,

#2771
