### ISSUE TITLE
Error thrown when opening receive modal

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3235]
```
react-dom.development.js?61bb:67 Warning: React does not recognize the `data-testId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `data-testid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at button
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:56:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/button/index.esm.js:168:24)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:56:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:56:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/stack.esm.js:26:24)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:56:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:56:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:56:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at Flag (webpack-internal:///./src/app/components/layout/flag.tsx:29:3)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:56:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/stack.esm.js:26:24)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:56:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at Suspense
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:56:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:56:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:56:66)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:56:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:56:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at eval (webpack-internal:///./src/app/components/drawer/base-drawer.tsx:51:5)
    at ReceiveModal (webpack-internal:///./src/app/pages/receive-tokens/receive-modal.tsx:51:108)
    at RenderedRoute (webpack-internal:///./node_modules/react-router/dist/index.js:715:5)
    at Outlet (webpack-internal:///./node_modules/react-router/dist/index.js:1119:26)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:56:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/stack.esm.js:26:24)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:56:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/stack.esm.js:26:24)
    at HomeLayout (webpack-internal:///./src/app/pages/home/components/home.layout.tsx:21:5)
    at HomeContainer (webpack-internal:///./src/app/pages/home/home.tsx:65:3)
    at HomeLoader (webpack-internal:///./src/app/pages/home/home.loader.tsx:16:3)
    at Home
    at AccountGate (webpack-internal:///./src/app/routes/account-gate.tsx:29:3)
    at RenderedRoute (webpack-internal:///./node_modules/react-router/dist/index.js:715:5)
    at Outlet (webpack-internal:///./node_modules/react-router/dist/index.js:1119:26)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:56:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:56:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at ContainerLayout (webpack-internal:///./src/app/features/container/container.layout.tsx:16:5)
    at Container (webpack-internal:///./src/app/features/container/container.tsx:19:100)
    at RenderedRoute (webpack-internal:///./node_modules/react-router/dist/index.js:715:5)
    at Routes (webpack-internal:///./node_modules/react-router/dist/index.js:1210:5)
    at AppRoutesAfterUserHasConsented (webpack-internal:///./src/app/routes/app-routes.tsx:106:69)
    at AppRoutes (webpack-internal:///./src/app/routes/app-routes.tsx:288:96)
    at ErrorBoundary (webpack-internal:///./src/app/features/errors/error-boundary.tsx:19:1)
    at AppErrorBoundary (webpack-internal:///./src/app/features/errors/app-error-boundary.tsx:86:3)
    at Router (webpack-internal:///./node_modules/react-router/dist/index.js:1142:15)
    at HashRouter (webpack-internal:///./node_modules/react-router-dom/dist/index.js:371:5)
    at Suspense
    at ColorModeProvider (webpack-internal:///./node_modules/@stacks/ui/dist/color-modes/index.esm.js:34:26)
    at QueryClientProvider (webpack-internal:///./node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:47:3)
    at ThemeSwitcherProvider (webpack-internal:///./src/app/common/theme-provider.tsx:46:3)
    at ThemeProvider (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:95:64)
    at ThemeProvider (webpack-internal:///./node_modules/@stacks/ui/dist/theme-provider.esm.js:19:25)
    at PersistGate (webpack-internal:///./node_modules/redux-persist/es/integration/react.js:38:5)
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:15:3)
    at App
```

**Comment by markmhendrickson** [comment]
This happen just once in a particular context?

**Comment by kyranjamie** [comment]
Maybe you can take a look at this one @fbwoolf  as I know you were making changes with data testid
