### ISSUE TITLE
Add signRawTX API endpoint for Bitcoin transactions

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3867]
To facilitate a wider range of transaction types for apps without requiring us to build custom flows for them (e.g. Stamps with https://github.com/hirosystems/wallet/issues/3714#issuecomment-1586153882)

**Comment by Iheff** [comment]
Just tagging into comment stream for noticifactionss on this

**Comment by Iheff** [comment]
Here is a great example of decoding counterparty data out of the txs involved.
https://jpja.github.io/Electrum-Counterparty/decode_tx.html?tx=29c0ca770c4057301c6bcd3885b1749f50caf61ba04bdeea51b8e5c4e0255d01 (example is a stamp issuance) which i thought might be helpful if you want to give any deeper TX information to signers of messages.

Cheers.

**Comment by kyranjamie** [comment]
If I'm not mistaken, you can turn raw transactions into PSBTs:

- Bitcoin Core `convertopsbt` https://bitcoincore.org/en/doc/0.18.0/rpc/rawtransactions/converttopsbt/
- `@scure/btc-signer` `btc.Transaction.fromRaw(xxx).toPSBT()`

Can't you use these methods to send stamps? @Iheff

**Comment by Iheff** [comment]
I could then feed that pbst into hiro?

I have to admit I am wholley unknoweldgable on pbst, but I will certainly chase this and try to use it (looks like i can feed these functions what I have already)
This certainly sounds promising. thank you - I wil feedback later with findings.

**Comment by Iheff** [comment]
It seems that @scure/btc-signer's btc.Transaction.fromRaw() expects a signed transaction to decode into a pbst. I've replicated the arguments the function might want anyway, but it fails on the functions first lines which appa are to decode the TX.
<img width="321" alt="image" src="https://github.com/hirosystems/wallet/assets/1042979/ddd69885-0d01-4be8-90e1-f9fd05003105">

...and as I'm just working with FE code, I wouldnt be able to just use cli for the converttopbst.

I need (ideally) to pass in a full unsigned raw TX for Hiro to then sign. 

I _can_ destructure the raw tx... so if there is a way for me to parse that and have hiro sign the parts, could I eventually form a pbst in that way?

**Comment by Iheff** [comment]
I have tried converting to PBST and must still be going wrong in the way i convert my initial TX to the the other (@scure/btc-signer) tx, as the signedTX I get back from that is refused as a broadcastable tx to the mempool.

I feel I am very close to a working model here - even have a nice prviewe of the ins and outs that seems correct within hiro before confirmation. Probably some eyes that are more familiar with hiro can assist to get over the hurdle.... failing this Ill have to rely on the fact that signrawTX might be coming - how are we looking there?

**Comment by razr22** [comment]
bump

>

**Comment by razr22** [comment]
> It seems that @scure/btc-signer's btc.Transaction.fromRaw() expects a signed transaction to decode into a pbst. I've replicated the arguments the function might want anyway, but it fails on the functions first lines which appa are to decode the TX. <img alt="image" width="321" src="https://user-images.githubusercontent.com/1042979/247638954-ddd69885-0d01-4be8-90e1-f9fd05003105.png">
> 
> ...and as I'm just working with FE code, I wouldnt be able to just use cli for the converttopbst.
> 
> I need (ideally) to pass in a full unsigned raw TX for Hiro to then sign.
> 
> I _can_ destructure the raw tx... so if there is a way for me to parse that and have hiro sign the parts, could I eventually form a pbst in that way?

bump

**Comment by kyranjamie** [comment]
@Iheff @razr22 it would greatly help us if you could put together a demo tx case in a live editor environment, ala https://codesandbox.io, where you have a test private key and create and sign the transaction identical to how you want the Hiro Wallet to.

This way, we can test against the wallet, and be sure we're offering you the functionality you need.

**Comment by Iheff** [comment]
My starting point previous to this was an API response from the counterparty API, which I just get freewallet to sign via app specific counterperty:signRawTx=true style link - so is pretty hands off code wise.

Formulating the TXs from scratch is new to me, but seems to be the right way to get the op data required into the hiro-style PBST instead.

I will endevour to provide a reduced/limited test case for you, however I can point your here to a chap who has made some Counteprarty TXs work but using stored keys: https://github.com/valperez715/stampwallet/blob/main/pages/account/sendSrc20.jsx#L23 which may offer some clues. https://github.com/valperez715/stampwallet/blob/main/service/bitcoin.js line 458 down seem to show them adding the CP data to the scripts.

**Comment by Iheff** [comment]
> This way, we can test against the wallet, and be sure we're offering you the functionality you need.

Hiya @kyranjamie - I made a simple repo here https://github.com/Iheff/hiro-react-sample
with some barebones stuff that hopes to use hiro to make a TX, I am able to generate a TX but it doesnt seem valid yet (mempooltest debugging says it is missing inputs) hopefully we can use this repo and starting off with a working simple bitcoin multi output tx,  and then try to work up to including the CP data too.

I did try both stackblitz and code-sandbox for this but both seemed to have issues with running everything together.

Ill try and prep something that could utilise the proposed signRawTX() function for you in the next few days too.

**Comment by kyranjamie** [comment]
Hi @Iheff, running through the code, I believe the problem is that you're treating the returned hex as a signed transaction. It isn't. We return a PSBT. For example, there are use-cases where other parties might have additional signatures to add.

If you want to sign it, you need to finalise the tx, then broadcast it. With the `@scure/btc-signer` lib, you do this with:

```ts
import * as btc from '@scure/btc-signer';
const hexRespFromHiro = resp.result.hex;
const tx = btc.Transaction.fromPSBT(hexToBytes(hexRespFromHiro));
tx.finalize();
testMempool(tx.hex);
```

[I've added a section to our docs describing how to do this →](https://hirowallet.gitbook.io/developers/bitcoin/sign-transactions/partially-signed-bitcoin-transactions-psbts#broadcasting-a-transaction)

**Comment by Iheff** [comment]
I have made the advised changes, - i now get error messages about 'previous outputs' but when debugging/tracing that error it looks related to the fees - which i feel we still need to set somewhere.
Repo has been updated to reflect your advice so far and so you can see the new error log.

```
ERROR
    Cannot find previous output info.
    at Transaction.prevOut (http://localhost:3000/static/js/bundle.js:70203:71)
    at get fee [as fee] (http://localhost:3000/static/js/bundle.js:70105:28)
    at createTransaction (http://localhost:3000/static/js/bundle.js:154:20)
```

I let the user slide a sat/bytes slider to set their rate and give an esitmate of fees, so I should be able to allow them to modify/confirm the rate at this stage - once i can set it, lol.

for 'signAtIndex' I am providing the index of each input (as this user should own all those inputs) - is that the correct thinking?

**Comment by kyranjamie** [comment]
I would recommend you try creating and broadcasting a transaction without Hiro Wallet, to make sure you're constructing it correctly. This will help you verify that your own implementation works.

For example

https://github.com/Iheff/hiro-react-sample/blob/master/src/interactions.js#L108

You're passing the index of the array of UTXOs to the `addInput` function. It expects the output index of the transaction being spent. This would explain why it can't find the output info.

**Comment by Iheff** [comment]
> You're passing the index of the array of UTXOs to the addInput function. It expects the output index of the transaction being spent. This would explain why it can't find the output info.

The transaction being spent is the input though right?

so, is that the 'vout' ?

```
 txHiro.addInput({...inputs[i], index:inputs[i].vout});
```


> I would recommend you try creating and broadcasting a transaction without Hiro Wallet, to make sure you're constructing it correctly. 


to do that, I have to learn alot of stuff I am not really interested in.......  to do this without hiro I can simply query counterparty API and get back a tx to sign, I don't have to build anything to faciliatate that - I am just trying to workaround this here for the hiro use-case, I just need a working trnasaction that I can then tuck some counterparty data into.

If there is no base example provided for how to compose a full tx I may as well forget Hiro for a while  because i just dont have time to learn all of bitcoin and I'll just have to hold on for the 'signRawTx' stuff.

Thank you so much for your help so far.

after reading deeper, i can see that my call for inputs that loads UTXO data is lacking some fields including preivousOutputTX and index.... I imagine this will be another API call, or a switch to an endpoint that fetches this data - any suggestions apreciated.
