### ISSUE TITLE
Unexpected application error listing transferring stamp or SRC-20 on openstamp.io with Leather

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4215]
Steps to reproduce
1. Sign in on openstamp.io with a wallet that has stamps/SRC-20 tokens
2. Go to assets via the top right menu
3. Transfer a token, click confirm
4. see error (note: if the wallet does not have enough BTC to cover the fee no error will be displayed accept in the console)

Issue with a Stamp:
![image](https://github.com/leather-wallet/extension/assets/33360391/216dce7b-49f4-4edc-8b59-5bba0dac5131)

`Unexpected Application Error!
Unknown address type=unknown
Error: Unknown address type=unknown
    at Object.encode (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/579.js:200337:19)
    at getAddressFromOutScript (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:47508:93)
    at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:23824:76
    at Array.map (<anonymous>)
    at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:23819:42
    at Object.useMemo (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/579.js:144338:189)
    at exports.useMemo (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/579.js:150572:208)
    at useParsedOutputs (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:23819:27)
    at useParsedPsbt (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:23958:25)
    at PsbtSigner (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:24093:7)
    at Xh (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/579.js:144321:137)
    at Wk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/579.js:144444:337)
    at Vk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/579.js:144434:389)
    at Uk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/579.js:144434:320)
    at Jk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/579.js:144434:180)
    at Ok (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/579.js:144425:88)
    at Fk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/579.js:144427:300)
    at jg (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/579.js:144281:105)
    at Xk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/579.js:144437:470)
    at Qk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/579.js:144435:398)
    at Hk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/579.js:144424:269)
    at J (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/579.js:158098:203)
    at MessagePort.R (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/579.js:158099:128)`

Issue as seen with an SRC-20 transfer
![image](https://github.com/leather-wallet/extension/assets/33360391/79bc851d-b02f-4729-b6c8-cb0ca359912e)

**Comment by markmhendrickson** [comment]
@fbwoolf I presume this is resolved by https://github.com/leather-wallet/extension/pull/4168?

**Comment by btcopenstamp** [comment]
@markmhendrickson @fbwoolf 

Hi. I am not sure what happened.  The src20 transfer function worked fine on previous published Hiro version, or testing package at https://github.com/leather-wallet/extension/pull/4060.

However, the current situation on OpenStamp is,

1. the transfer of SRC20 will fail just like the issue reported 
2. the transfer of Image Stamps works fine.

**Comment by 314159265359879** [comment]
I just received some questions on x.com it looks like they have an idea why SRC transactions can't be signed or perhaps they can assess if/how it relates to #4060 (if so). Directing them to this conversation.

![image](https://github.com/leather-wallet/extension/assets/33360391/9d892d35-ec98-4b78-9a25-fa0a966eabe0)

**Comment by btcopenstamp** [comment]
@fbwoolf @markmhendrickson With SRC20 gaining popularity, many Leather users are moving to Unisat for its bare multi-sig output support. We suggest that the Leather team can help consider adding this feature.

**Comment by fbwoolf** [comment]
@btcopenstamp can you test this again to see if it is working for you after I rebased it on our current dev branch, thanks? https://github.com/leather-wallet/extension/pull/4060

We are going to get it merged if it is still able to unblock you.

**Comment by btcopenstamp** [comment]
@fbwoolf Hi. It works fine with transfer SRC20 tokens based on this build. But still failed on #3897 .

**Comment by btcopenstamp** [comment]
@fbwoolf Hi. It works fine both on this issue and  #3897. Great to know that.

**Comment by fbwoolf** [comment]
@markmhendrickson want me to merge the PR?

**Comment by markmhendrickson** [comment]
Yep please! 🙏
