### ISSUE TITLE
Swaps broken when no bitcoin keys available

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4319]
```
Unexpected Application Error!
No signer
Error: No signer
    at chrome-extension://kepoednijakempabkblheecenlndgdmb/index.js:168602:24
    at mountMemo (chrome-extension://kepoednijakempabkblheecenlndgdmb/index.js:290555:19)
    at Object.useMemo (chrome-extension://kepoednijakempabkblheecenlndgdmb/index.js:291000:16)
    at useMemo (chrome-extension://kepoednijakempabkblheecenlndgdmb/index.js:314643:21)
    at useCurrentAccountNativeSegwitIndexZeroSigner (chrome-extension://kepoednijakempabkblheecenlndgdmb/index.js:168601:56)
    at SwapContainer (chrome-extension://kepoednijakempabkblheecenlndgdmb/index.js:156556:151)
    at renderWithHooks (chrome-extension://kepoednijakempabkblheecenlndgdmb/index.js:289635:18)
    at mountIndeterminateComponent (chrome-extension://kepoednijakempabkblheecenlndgdmb/index.js:293399:13)
    at beginWork (chrome-extension://kepoednijakempabkblheecenlndgdmb/index.js:294912:16)
    at beginWork$1 (chrome-extension://kepoednijakempabkblheecenlndgdmb/index.js:300751:14)
💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own ErrorBoundary or errorElement prop on your route.
```

Swaps breaks when using Ledger with no Bitcoin keys. Ensure components are structured such that the hooks are only called when there are bitcoin keys.

**Comment by markmhendrickson** [comment]
@kyranjamie I presume this is resolved by now and we can close?
