### ISSUE TITLE
BRC20 send flow broken: unexpected application error

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4482]
Steps to reproduce
1. Clicking send in the wallet
2. Picking any BRC-20 token
3. Clicking continue

Unexpected Application Error!
[BigNumber Error] Argument not a primitive number:
Error: [BigNumber Error] Argument not a primitive number: 
    at intCheck (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/905.js:257254:11)
    at P.shiftedBy (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/905.js:256769:5)
    at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:4522:26
    at useBrc20SendForm (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:33998:113)
    at Brc20SendForm (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:34042:7)
    at Xh (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/905.js:188734:137)
    at dj (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/905.js:188764:258)
    at Wk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/905.js:188859:88)
    at Vk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/905.js:188847:389)
    at Uk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/905.js:188847:320)
    at Jk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/905.js:188847:180)
    at Ok (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/905.js:188838:88)
    at Fk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/905.js:188840:300)
    at jg (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/905.js:188694:105)
    at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/905.js:188834:273

**Comment by 314159265359879** [comment]
By the way, when I add an amount, I do not see this error pop up.

**Comment by fbwoolf** [comment]
@alter-eggo, I've been working on this today and feel like I have a fix for this specific bug ...but then I run into quite few other things that are a bit strange with the routing. I think maybe you have more context on the implementation here? Reassign to me if you don't!
