### ISSUE TITLE
Send STX form is crashing 

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#5145]
When starting to work on [this](https://github.com/leather-wallet/extension/issues/5133), I realised that the send STX flow is crashing with:
```
Unexpected Application Error!
Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
    at formSip10TxSummary (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:186214:48)
    at formReviewTxSummary (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:186188:14)
    at StacksSendFormConfirmation (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:201968:7)
    at renderWithHooks (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:280887:18)
    at updateFunctionComponent (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:284165:20)
    at beginWork (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:286178:16)
    at beginWork$1 (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:292003:14)
    at performUnitOfWork (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:291134:12)
    at workLoopSync (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:291043:5)
    at renderRootSync (chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.js:291011:7)
```

It also tries to move to the wrong route for `confirm` -> `/send/stx/confirm/confirm` 

I tested and it's not happening on `main` but it is on the `dev` branch

**Comment by pete-watters** [comment]
The send BTC flow is also not working and similarly, redirecting to the wrong place 

https://github.com/leather-wallet/extension/assets/2938440/44f37dd8-b3d8-4540-9780-0df7bd5123ff
