### ISSUE TITLE
Fix 500 error encountered with sendTransfer API

### ISSUE THREAD

**Issue by mikeywaites** [blockstack/blockstack-app#5250]
We are seeing a persistent issue trying to send bitcoin tx from LeatherProvider as a request to ordinals explorer seems to throw a 500 resulting in the rpc call to crash

```
inscriptions.query.ts:258 
 GET https://ordinals-explorer.generative.xyz/output/f30ac99…:1 500 (Internal Server Error)
logger.ts:51 Error broadcasting tx TypeError: Cannot read properties of undefined (reading 'url')
    at getInscriptionsByTransactionId (bitcoin-client.ts:136:15)
    at use-check-utxos.ts:62:64
    at Array.map (<anonymous>)
    at checkInscribedUtxosByBestinslot (use-check-utxos.ts:62:54)
    at use-check-utxos.ts:147:40
    at async use-bitcoin-broadcas…ransaction.ts:45:37
    at async onUserApproveSendTransferRequest (rpc-send-transfer-confirmation.tsx:92:5)
```
﻿
﻿
<img width="1037" alt="image" src="https://github.com/leather-wallet/extension/assets/488217/14d370e2-08af-4962-8625-8dc0a2af1cbf">

```
  executeTransfer: async (transaction: Transaction) => {
    try {
      const resp = await window.LeatherProvider?.request("sendTransfer", {
        network: "mainnet",
        recipients: [
          {
            address: transaction.destination_address,
            amount: transaction.amount.toString(),
            from: transaction.sending_address,
          },
        ],
      });
      return { txId: resp?.result.txid || null };
    } catch (err) {
      console.log(err);
      throw err;
    }
  },
```
 
we have a project going live in < 12 hours. would great if someone could shed some light on this issue or point out if we're doing something wrong here.

**Comment by mikeywaites** [comment]
Just dropping this here as i think this could be related to the issue i posted earlier
https://github.com/leather-wallet/extension/issues/5250

**Comment by markmhendrickson** [comment]
Thanks for the report – we'll investigate ASAP today.
