### ISSUE TITLE
Switching to mainnet <-> testnet network on extension with ledger device leads to error: No signer

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5251]
Edge browser, Ledger nano S OS version 1.1.1
Wallet version 6.34.0

Refreshing page or reloading and clearing cache had no effect. Reinstalled the wallet to resolve the error from showing and being able to proceed with wallet. 

![image](https://github.com/leather-wallet/extension/assets/33360391/d0a51645-0211-4eb5-b2f8-501309bed957)

````
console.js:36  React Router caught the following error during render 
Error: No signer
    at taproot-account.hooks.ts:91:24
    at Object.Ci [as useMemo] (react-dom.production.min.js:179:117)
    at exports.useMemo (react.production.min.js:25:191)
    at useCurrentAccountTaprootIndexZeroSigner (taproot-account.hooks.ts:90:17)
    at AssetsList (asset-list.tsx:28:85)
    at Xh (react-dom.production.min.js:167:135)
    at dj (react-dom.production.min.js:197:256)
    at Wk (react-dom.production.min.js:292:18)
    at Vk (react-dom.production.min.js:280:383)
    at Uk (react-dom.production.min.js:280:319)
    at Jk (react-dom.production.min.js:280:180)
    at Ok (react-dom.production.min.js:271:86)
    at Fk (react-dom.production.min.js:273:286)
    at jg (react-dom.production.min.js:127:100)
    at react-dom.production.min.js:267:262 {componentStack: '\n    at AssetsList (chrome-extension://ldinpeekobn…hjjdofggfgjlcehhmanlj/951.js:248331:3)\n    at App'}

**Comment by 314159265359879** [comment]
reproduction steps
1. install wallet
2. connect ledger
3. switch from mainnet network to testnet
4. see error

**Comment by 314159265359879** [comment]
Looks like some users hit this error when they try to connect their ledger device.

**Comment by pete-watters** [comment]
I tested this on this branch and it seems to fix the issue [5254](https://github.com/leather-wallet/extension/pull/5254)
