### ISSUE TITLE
Multiple errors when using custom Stacks API

### ISSUE THREAD

**Issue by hstove** [blockstack/blockstack-app#5996]
I've been trying to use Leather (6.54.0) with Nakamoto Testnet, but I've hit two different errors.

One, when switching to an existing network I've configured before for Nakamoto Testnet, I get this right after clicking the network in the network switching dialogue:

```
TypeError: useNativeSegwitAccountBuilder(...) is not a function
    at useNativeSegwitSigner (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:31374:50)
    at useCurrentAccountNativeSegwitSigner (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:31389:10)
    at useCurrentAccountNativeSegwitAddressIndexZero (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:31406:18)
    at Home (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:16705:107)
    at Nh (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103245:137)
    at cj (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103281:258)
    at Vk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103376:88)
    at Uk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103364:389)
    at Tk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103364:320)
    at Ik (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103364:180)
    at Nk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103355:88)
    at Ek (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103357:300)
    at jg (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103212:105)
    at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103351:273
```

And then I can add a new Nakamoto Testnet, which gets me past that error, but I get this error when I try and submit a transaction:

```
TypeError: generateAccount is not a function
    at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:31358:38
    at recomputationWrapper (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:255254:25)
    at memoized (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:255191:21)
    at dependenciesChecker (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:255266:39)
    at memoized (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:255191:21)
    at memoized (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:248874:28)
    at a (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:128804:204)
    at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:128804:420
    at Object.useSyncExternalStore (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103263:368)
    at push.32713.exports.useSyncExternalStore (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:106971:309)
    at push.85317.exports.useSyncExternalStoreWithSelector (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:128804:489)
    at useSelector2 (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:248881:27)
    at useCurrentNativeSegwitAccount (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:31361:77)
    at useHasCurrentBitcoinAccount (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:31132:93)
    at useConfigBitcoinEnabled (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:30593:152)
    at TotalBalanceSuspense (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:2514:83)
    at Nh (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103245:137)
    at Vk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103374:337)
    at Uk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103364:389)
    at Tk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103364:320)
    at Ik (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103364:180)
    at Nk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103355:88)
    at Ek (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103357:300)
    at jg (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103212:105)
    at Wk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103367:470)
    at Pk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103365:398)
    at Gk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:103354:269)
    at J (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:114921:203)
    at MessagePort.R (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/61.js:114922:128)
```

**Comment by hstove** [comment]
Another note is that, when creating the network, I get an error "Cannot determine ChainID from node". This error happens if I specify mainnet and testnet4 as the Bitcoin network. It seems to work if I select regtest or testnet3. When it works, it shows 0 Stacks balance, which I'm guessing is because it's querying an SPXXX (mainnet) address due to chainID stuff.

**Comment by 314159265359879** [comment]
@camerow

**Comment by markmhendrickson** [comment]
@camerow let's prioritize this during the current cycle given its relation to sBTC?

**Comment by camerow** [comment]
Yeah, agreed. Calling in the big gun: @alter-eggo

**Comment by markmhendrickson** [comment]
@alter-eggo resurfacing

**Comment by alter-eggo** [comment]
@hstove can you please tell what urls you provide here?

![Image](https://github.com/user-attachments/assets/eb226a3e-b31b-467b-b9c7-25f747cdef93)

**Comment by hstove** [comment]
I was using `https://api.nakamoto.testnet.hiro.so`, but that's no longer a thing. I made no change to the Bitcoin API URL.

**Comment by alter-eggo** [comment]
@hstove are there other url I can use to check?

**Comment by camerow** [comment]
@alter-eggo how's progress going here, do you need me to help track down any more information?

**Comment by alter-eggo** [comment]
@camerow I cannot replicate the issue without url to test 🤔

**Comment by hstove** [comment]
Hey @alter-eggo @camerow , I was able to find a different network's URL that repros the problem: https://api.nakamoto-2.hiro.so

**Comment by camerow** [comment]
Thank you @hstove!

**Comment by alter-eggo** [comment]
hm, it's not event possible to add network with such url
network id on this url [here](https://api.nakamoto-2.hiro.so/v2/info) is 512, though as I see from the code [we support only `2147483648`](https://github.com/leather-io/extension/blob/dev/src/app/features/add-network/use-add-network.tsx#L178-L192)
```
export declare enum ChainID {
    Testnet = 2147483648,
    Mainnet = 1
}
```
<img width="786" alt="Image" src="https://github.com/user-attachments/assets/0324f25a-e3ee-4e91-a3ab-7f53c8f07e8f" />

**Comment by kyranjamie** [comment]
Do we need to add a configuration to allow different chain IDs then, or can we infer it by calling the API?

**Comment by hstove** [comment]
Yep you can infer it from the URL, `/v2/info` gives `network_id` aka ChainID

**Comment by alter-eggo** [comment]
@kyranjamie maybe call the api (url/v2/info) and check if network id is there? if yes - validation passed?

**Comment by alter-eggo** [comment]
fixed validation here: https://github.com/leather-io/extension/pull/6093
added network with https://api.nakamoto-2.hiro.so/ and it works ok

**Comment by markmhendrickson** [comment]
@alter-eggo is this issue fully resolved or pending more work?

**Comment by alter-eggo** [comment]
@markmhendrickson I believe this one was resolved
but cannot test with urls provided in the issue, they are unreachable

**Comment by markmhendrickson** [comment]
@hstove could you help test this issue again to see if it's resolved?
